apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-app-config
data:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_TABLE: "postgres"
  DB_PORT: "5432"
  DB_SSL_MODE: "disable"
  MIGRATION_PATH: "file://../../migrations"
